<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Exe</OutputType>
    <RootNamespace>Extensions.Hosting.PluginService.Platform.Tests</RootNamespace>
    <SolutionDir>$(MSBuildThisFileDirectory)..\..\..\</SolutionDir>
    <SolutionName>Extensions.Hosting</SolutionName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Extensions.Hosting.PluginService\Extensions.Hosting.PluginService.csproj" />
    <ProjectReference Include="..\..\..\Extensions.Hosting.Plugins\Extensions.Hosting.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Extensions.Hosting.PluginService\log4net.config" Link="log4net.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="TUnit.Assertions" />
    <Using Include="TUnit.Assertions.Extensions" />
    <Using Include="TUnit.Core" />
  </ItemGroup>
</Project>
