<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows10.0.19041;net11.0-windows10.0.19041</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <IsTestProject>true</IsTestProject>
    <GenerateProgramFile>false</GenerateProgramFile>
    <RootNamespace>Extensions.Hosting.ReactiveUI.Wpf.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Extensions.Hosting.ReactiveUI.Wpf\Extensions.Hosting.ReactiveUI.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="TUnit.Assertions" />
    <Using Include="TUnit.Assertions.Extensions" />
    <Using Include="TUnit.Core" />
  </ItemGroup>
</Project>
